export default function StressTestPage() {
  return (
    <div>
      <h1 className="text-2xl font-semibold mb-2">Stress test</h1>
      <p className="text-sm text-neutral-400 mb-8">
        Hand-picked occlusion clips from DanceTrack-val. The leaderboard below is regenerated by
        <code className="mx-1 px-1 bg-neutral-900 rounded">scripts/run_stress_test.py</code>
        as new tracker variants are added.
      </p>

      <table className="text-sm border border-neutral-800 w-full max-w-2xl">
        <thead className="bg-neutral-900 text-neutral-300">
          <tr>
            <th className="px-3 py-2 text-left">Tracker</th>
            <th className="px-3 py-2 text-right">MOTA</th>
            <th className="px-3 py-2 text-right">IDF1</th>
            <th className="px-3 py-2 text-right">HOTA</th>
            <th className="px-3 py-2 text-right">IDSW</th>
          </tr>
        </thead>
        <tbody className="text-neutral-400">
          {['sort', 'deepsort', 'bytetrack'].map((t) => (
            <tr key={t} className="border-t border-neutral-800">
              <td className="px-3 py-2">{t}</td>
              <td className="px-3 py-2 text-right">—</td>
              <td className="px-3 py-2 text-right">—</td>
              <td className="px-3 py-2 text-right">—</td>
              <td className="px-3 py-2 text-right">—</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="mt-6 text-xs text-neutral-500">
        Numbers populated after detector fine-tune (week 5) and stress-test run (week 8). See
        <code className="mx-1 px-1 bg-neutral-900 rounded">docs/TECHNICAL_DESIGN.md</code>.
      </p>
    </div>
  );
}
